
#pragma once
#define ST7735_NUM_DEVICES 1
#define QUANTUM_PAINTER_DISPLAY_TIMEOUT 0
#define SPLIT_MODS_ENABLE
#define SPI_DRIVER SPID0
#define SPI_SCK_PIN GP2
#define SPI_MOSI_PIN GP3
#define SPI_MISO_PIN GP29
#define LCD_DC_PIN GP5
#define LCD_CS_PIN GP6
#define LCD_RST_PIN GP4
#define LCD_SPI_DIVISOR 8
#define QUANTUM_PAINTER_DEBUG
#define QUANTUM_PAINTER_SUPPORTS_NATIVE_COLORS true
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U
#define DEBUG_MATRIX_SCAN_RATE

#ifndef BOOTMAGIC_LITE_ROW
#define BOOTMAGIC_LITE_ROW 0
#endif

#ifndef BOOTMAGIC_LITE_COLUMN
#define BOOTMAGIC_LITE_COLUMN 0
#endif
